### ISSUE TITLE
Logistics/attributions question regarding distributing/deploying your Library in/with our Docker environments

### ISSUE THREAD

**Issue by DiegoPino** [dbmdz/solr-ocrhighlighting#135]
@jbaiter good morning. 

We moved faster this week and have a semi-working workflow that includes miniOCR transformation and quite happy!
Now that we know this works great for us (thanks again for coding this!), i would (respectfully) ask you what guidelines you have (README files, Licenses, attributions, mentions in releases, etc) for delivering the Solr plugin/using it in other projects.

I do not want to hide your work by pushing it into our docker machinery.  (e.g deploying it via a DockerFile and building it into it our containers) So, some better options could be:

- Easiest for our users: we fetch and copy into a folder in our GitHub on each of our releases (e.g here is an open pull where I can test https://github.com/esmero/archipelago-deployment/pull/73 ) with any accompanying data from your site you feel is needed to be distributed with, and then bind mount it at a given path on our the Solr Container 
- Less invasive/respectful, each time our users deploy I run a script that gets it with Licences and Readme from your GitHub repo. Nothing is stored on our side
- Middle-ground option, we add a script that deploys it if not present via our docker-compose (like what you do in your integration tests)

Hope I'm not making too much of a fuzz, we just want to be thoughtful of your work and make sure our users are aware their highlights are because of your wonderful plugin.

Besides of the 3 options (and any other ones you can suggest) we also want to make sure to attribute your work correctly (you alone, is there a larger team?) and would love to know how that works better for you. Same goes with Licenses/ correct naming, etc.

Will also, based on your response, make sure you get into our release notes.

Best

**Comment by jbaiter** [comment]
Diego, thank you, I really appreciate the sentiment! I think it's perfectly fine if you stick with the terms of the MIT license, which basically just requires you to include the name of the project, the copyright holder (the Bavarian State Library) and the license with any distributions. This is all part of the `pom.xml` that is included in the plugin JAR, so I think as long as you don't remove it from there, you're good :-)

That being said, if you want to go beyond that, a mention in your README/docs would be great, maybe this can attract more users that can help with useful bug reports and make the plugin better :-) Also, if we get  to the point were we want to add testimonials to the README, I'd appreciate if I could mention Archipelago!

Also, just as a heads up, I'm thinking of changing the name to `solr-ocrsearch` with the next release, since it adds a feature that goes beyond the pure highlighting use case.

**Comment by giancarlobi** [comment]
@jbaiter Thanks a lot, it's a pleasure collaborate with you! I'm looking forward to check new release and new features.

**Comment by DiegoPino** [comment]
@jbaiter great! We will work in the next days on our final implementation and will add the details (and share for your revision) to our upcoming release notes and documentation. Will also make a post to our google post (probably next week) making sure I spread the word of your work and this plugin and will share with you.

Happy to contribute to any testimonials when you feel you want to do that. Very grateful.

Hugs
