### ISSUE TITLE
Sort snippets like in the text

### ISSUE THREAD

**Issue by Sozialarchiv** [dbmdz/solr-ocrhighlighting#151]
Is it possible to sort the snippets by the order they occur in the text (ocr file)? I could not find it in the documentation.

**Comment by jbaiter** [comment]
This is currently not possible, since we rely on Solr's unified highlighter for sorting the candidate passages before extracting the bounding boxes and the context.
It works by treating each passage (a block of text with one or more occurences of the query) as an individual document and then applying TF-IDF or BM25 on it to score the passage in the context of the document.
The aim is to return the "most relevant" passages from the result set first.

I think it should be possible to make this configurable via a request parameter and then sort the passages by their offset in the OCR file instead of their score.

**Comment by Sozialarchiv** [comment]
Thank you very much for your answer.

**Comment by jbaiter** [comment]
This has now been implemented and will be available in the next stable release:
https://github.com/dbmdz/solr-ocrhighlighting/commit/6d7596ed69e2749854f46f0144c57a5794d19dce

If you want to use it sooner, follow the instructions in the README to build a development snapshot :-)

**Comment by Sozialarchiv** [comment]
That is really amazing. Thank you very much for the fast implementation.
