### ISSUE TITLE
Error while SOLR indexing of document without OCR

### ISSUE THREAD

**Issue by beatrycze-volk** [dbmdz/solr-ocrhighlighting#167]
We have installed new version (0.6.0) and tried to index documents without OCR field or with empty OCR field. In both cases we are getting error:

`Caused by: java.lang.NegativeArraySizeException
	at de.digitalcollections.solrocr.reader.PeekingReader.<init>(PeekingReader.java:45)
	at de.digitalcollections.solrocr.lucene.filters.OcrCharFilterFactory.create(OcrCharFilterFactory.java:37)
	at org.apache.solr.analysis.TokenizerChain.initReader(TokenizerChain.java:97)`

Is there a possibility to index documents which are not containing OCR field or is there maybe some kind of placeholder which we could use for this problem?

**Comment by jbaiter** [comment]
Can confirm, this happens when the field value is an empty string. Just not including the field in the document does not cause any problems and works as expected.
I'm working on a fix, in the meantime try if you can find a way to tell your client library to simply skip a field if there's no value supplied for it.

**Comment by beatrycze-volk** [comment]
Thanks a lot!
