### ISSUE TITLE
Publicly available XSD for MiniOCR?

### ISSUE THREAD

**Issue by DiegoPino** [dbmdz/solr-ocrhighlighting#343]
Hallo!

Wanted to ask if you know of a publicly available XSD definition/or you all manage one for miniOCR? Or any proper good way of exposing its profile in a IIIF Manifest in a seeAlso structure?

 "seeAlso": {
            "@id": "https://SOME_URL_TO_MINIOCR?Page=1",
            "profile": "THIS QUESTION ABOUT AN XSD PROFILE URL",
            "format": "text/xml",
            "label": "MINI OCR XML for PAGE 1"
          },

Not urgent really, just an open question

Thanks a lot!

**Comment by jbaiter** [comment]
Nope, and I'm a bit wary of creating one tbh 😅

MiniOCR as of now is primarily intended as an internal format of the plugin, since it's pretty much tailored to our specific use case and is missing a ton of stuff you'd expect from a 'proper' markup format.

I'd say your best bet right now is to simply put the documentation URL into the `profile` field, just like you'd do with hOCR: https://dbmdz.github.io/solr-ocrhighlighting/0.8.1/formats/#miniocr
